name: palumba_eu
description: Palumba project with GetX and Provider

version: 0.8.0+493

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Common Modules
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5

  # Core Modules
  get: ^4.6.6
  provider: ^6.1.2

  # Native Specific Modules
  package_info_plus: ^6.0.0
  app_tracking_transparency: ^2.0.4

  # UI Modules
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  lottie: ^3.1.0
  path_drawing: ^1.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_widget_from_html_core: ^0.14.11
  smooth_page_indicator: ^1.1.0
  matrix4_transform: ^3.0.1

  # Localization Modules
  intl: ^0.18.1
  intl_utils: ^2.8.7

  # API Modules
  http: ^1.2.1

  # Reporting Modules
  sentry_flutter: ^7.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  adaptive_icon_background: "#FFFBF0"
  adaptive_icon_foreground: "assets/images/app_icons/img_fg.png"
  image_path: "assets/images/app_icons/img_ios.png"
  remove_alpha_ios: true


flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/utils/managers/i18n_manager/translations/l10n
  output_dir: lib/utils/managers/i18n_manager/translations/generated

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/flags/
    - assets/images/app_icons/
    - assets/anims/
    - .env.dev
    - .env.prod

    #fonts:
    #- family: fontFamily
    #  fonts:
    #    - asset: fonts/means/light.ttf
    #    - asset: fonts/means/medium.ttf
    #      weight: 700