name: flutter_boilerplate
description: A new Flutter project boilerplate with GetX and Provider

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0

  # Common Modules
  shared_preferences: ^2.0.7
  flutter_svg: ^0.22.0
  url_launcher: ^6.0.10
  flutter_svg_provider: ^0.1.10
  cached_network_image: ^3.1.0
  basic_utils: ^3.3.2
  uuid: ^3.0.5

  # SSO Modules
  sign_in_with_apple: ^3.2.0
  google_sign_in: ^5.1.0
  flutter_facebook_auth: ^3.5.2

  # Core Modules
  get_it: ^7.2.0
  get: ^4.3.8
  flutter_cache_manager: ^3.1.2
  path_provider: ^2.0.4
  diacritic: ^0.1.3
  provider: ^6.0.1
  jwt_decoder: ^2.0.1
  dart_jsonwebtoken: ^2.3.2
  flutter_secure_storage: ^5.0.2

  # Native Specific Modules
  app_tracking_transparency: ^2.0.2+1
  package_info: ^2.0.2
  app_review: ^2.1.1+1
  webview_flutter: ^2.0.4
  flutter_html: ^2.2.1

  # UI Modules
  lottie: ^1.2.1
  shimmer: ^2.0.0
  dotted_border: ^2.0.0+1
  flutter_sfsymbols: ^2.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  dotted_line: ^3.0.1

  # Geolocation Modules
  google_maps_flutter: ^2.0.9
  flutter_google_places: ^0.3.0
  geocoder:
    git:
      https://github.com/nguyenxdat/flutter_geocoder.git
  geolocator: ^7.7.0
  map_launcher: ^2.0.0

  # GraphQL Modules
  json_annotation: ^4.0.1
  equatable: ^2.0.3
  meta: ^1.3.0
  gql: ^0.13.0
  artemis: ^7.1.1-beta.1
  jose: ^0.3.2
  graphql_flutter: ^5.0.0
  gql_websocket_link: ^0.3.1

  # Firebase Modules
  firebase_messaging: any
  firebase_analytics: ^9.1.2
  firebase_dynamic_links: ^2.0.10
  firebase_in_app_messaging: any
  firebase_crashlytics: any
  firebase_remote_config: ^2.0.0

dev_dependencies:
  change_app_package_name: ^1.0.0 #flutter pub run change_app_package_name:main com.new.package.name
  pedantic: ^1.11.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

dependency_overrides:
  platform: ^3.1.0

flutter_icons: #flutter pub run flutter_launcher_icons:main
  android: "launcher_icon"
  ios: true
  image_path: "assets/appIcons/launcher_icon.png"


flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/utils/managers/i18n_manager/translations/l10n
  output_dir: lib/utils/managers/i18n_manager/translations/generated

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/appIcons/
    - assets/fonts/
    - assets/images/

    #fonts:
    #- family: fontFamily
    #  fonts:
    #    - asset: fonts/means/light.ttf
    #    - asset: fonts/means/medium.ttf
    #      weight: 700