name: flutter_boilerplate
description: A new Flutter project boilerplate with GetX and Provider

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.17.0

  # Common Modules
  shared_preferences: ^2.0.7
  flutter_svg: ^0.22.0
  flutter_svg_provider: ^0.1.10
  cached_network_image: ^3.1.0
  just_audio: ^0.9.20
  stop_watch_timer: ^1.3.1
  flutter_vibrate: ^1.3.0

  # Core Modules
  get_it: ^7.2.0
  get: ^4.3.8
  path_provider: ^2.0.4
  diacritic: ^0.1.3
  provider: ^6.0.1

  # Native Specific Modules
  app_review: ^2.1.1+1
  flutter_launcher_icons: ^0.9.2
  in_app_purchase: ^3.0.2

  # UI Modules
  lottie: ^1.2.1
  shimmer: ^2.0.0
  flutter_sfsymbols: ^2.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  dotted_line: ^3.0.1

#  # Firebase Modules
#  firebase_messaging: any
#  firebase_analytics: ^9.1.2
#  firebase_dynamic_links: ^2.0.10
#  firebase_in_app_messaging: any
#  firebase_crashlytics: any
#  firebase_remote_config: ^2.0.0

dev_dependencies:
  change_app_package_name: ^1.0.0 #flutter pub run change_app_package_name:main com.new.package.name
  pedantic: ^1.11.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

dependency_overrides:
  platform: ^3.1.0

flutter_icons: #flutter pub run flutter_launcher_icons:main
  android: "launcher_icon"
  ios: true
  image_path: "assets/appIcons/appIcon.png"


flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/utils/managers/i18n_manager/translations/l10n
  output_dir: lib/utils/managers/i18n_manager/translations/generated

flutter:
  uses-material-design: true
  assets:
    - assets/appIcons/
    - assets/fonts/
    - assets/images/
    - assets/audios/
    - assets/data.json

  fonts:
  - family: Means
    fonts:
      - asset: assets/fonts/means/regular.ttf

  - family: sficonsets
    fonts:
      - asset: packages/flutter_sfsymbols/fonts/sficonsets.ttf