name: palumba_eu
description: A new Flutter project boilerplate with GetX and Provider

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Common Modules
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2

  # Core Modules
  get: ^4.6.6
  provider: ^6.1.2

  # Native Specific Modules
  package_info_plus: ^6.0.0
  app_tracking_transparency: ^2.0.4
  # webview_flutter: ^4.7.0

  # UI Modules
  dui: 0.0.4
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  # auto_size_text: ^3.0.0

  # Localization Modules
  intl: ^0.18.1
  intl_utils: ^2.8.7

  # API Modules
  graphql_flutter: ^5.1.2
  graphql_codegen: ^0.13.11
  http: ^1.2.1
  jose: ^0.3.4

  # Firebase Modules
  firebase_messaging: ^14.7.20
  firebase_crashlytics: ^3.4.19
  #  firebase_analytics: ^10.8.10
  #  firebase_dynamic_links: ^5.4.18
  #  firebase_in_app_messaging: ^0.7.4+18

  # SSO Modules
  #  sign_in_with_apple: ^6.0.0
  #  google_sign_in: ^6.2.1
  #  flutter_facebook_auth: ^6.1.1

  # Geolocation Modules
  #  google_maps_flutter: ^2.6.0
  #  geolocator: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  dui: 0.0.4

flutter_icons: #flutter pub run flutter_launcher_icons:main
  android: "launcher_icon"
  ios: true
  image_path: "assets/appIcons/launcher_icon.png"


flutter_intl:
  enabled: true
  class_name: S
  main_locale: es
  arb_dir: lib/utils/managers/i18n_manager/translations/l10n
  output_dir: lib/utils/managers/i18n_manager/translations/generated

flutter:
  uses-material-design: true
  assets:
    - assets/appIcons/
    - assets/fonts/
    - assets/images/
    - .env.dev
    - .env.prod

    #fonts:
    #- family: fontFamily
    #  fonts:
    #    - asset: fonts/means/light.ttf
    #    - asset: fonts/means/medium.ttf
    #      weight: 700