name: palumba_eu
description: Palumba project with GetX and Provider

version: 2.0.3+1556

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Common Modules
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5

  # Core Modules
  get: ^4.6.6
  provider: ^6.1.2
  screenshot: ^3.0.0
  path_provider: ^2.1.3

  # Native Specific Modules
  package_info_plus: ^8.1.3
  share_plus: ^10.1.4

  # UI Modules
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  lottie: ^3.1.0
  path_drawing: ^1.0.1
  flutter_launcher_icons: ^0.14.3
  flutter_widget_from_html_core: ^0.15.2
  flutter_html: ^3.0.0-beta.2
  fl_chart: ^0.70.2
  syncfusion_flutter_charts: ^28.1.41
  smooth_page_indicator: ^1.1.0
  matrix4_transform: ^4.0.1
  appinio_swiper: ^2.1.1
  auto_size_text: ^3.0.0
  dotted_border: ^2.1.0
  flip_card: ^0.7.0

  # Localization Modules
  intl: ^0.19.0
  intl_utils: ^2.8.7

  # API Modules
  http: ^1.2.1

  # Reporting Modules
  sentry_flutter: ^8.0.0
  device_region: ^1.4.0
  plausible_analytics: ^0.3.0
  firebase_core: ^3.4.0
  firebase_messaging: ^15.2.1
  app_settings: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  adaptive_icon_background: "#FFFBF0"
  adaptive_icon_foreground: "assets/images/app_icons/img_fg.png"
  image_path: "assets/images/app_icons/img_ios.png"
  remove_alpha_ios: true


flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/utils/managers/i18n_manager/translations/l10n
  output_dir: lib/utils/managers/i18n_manager/translations/generated

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/election/de/
    - assets/images/election/eu/
    - assets/images/flags/
    - assets/images/app_icons/

  fonts:
    - family: caprasimo
      fonts:
        - asset: assets/fonts/caprasimo-regular.ttf

    - family: merriweather-black
      fonts:
        - asset: assets/fonts/merriweather-black.ttf

    - family: noto-serif-black
      fonts:
        - asset: assets/fonts/noto-serif-black.ttf

    - family: merriweather-sans
      fonts:
        - asset: assets/fonts/merriweather-sans-Bold.ttf
          weight: 700
        - asset: assets/fonts/merriweather-sans-Light.ttf
          weight: 300