name: palumba_eu
description: Palumba project with GetX and Provider

version: 0.9.1+945

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Common Modules
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5

  # Core Modules
  get: ^4.6.6
  provider: ^6.1.2
  widgets_to_image: ^0.0.3
  path_provider: ^2.1.3

  # Native Specific Modules
  package_info_plus: ^6.0.0
  app_tracking_transparency: ^2.0.4
  share_plus: ^8.0.3

  # UI Modules
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  lottie: ^3.1.0
  path_drawing: ^1.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_widget_from_html_core: ^0.14.11
  flutter_html: ^3.0.0-beta.2
  fl_chart: ^0.67.0
  syncfusion_flutter_charts: ^25.1.41
  smooth_page_indicator: ^1.1.0
  matrix4_transform: ^3.0.1
  appinio_swiper: ^2.1.1

  # Localization Modules
  intl: ^0.18.1
  intl_utils: ^2.8.7

  # API Modules
  http: ^1.2.1

  # Reporting Modules
  sentry_flutter: ^7.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  adaptive_icon_background: "#FFFBF0"
  adaptive_icon_foreground: "assets/images/app_icons/img_fg.png"
  image_path: "assets/images/app_icons/img_ios.png"
  remove_alpha_ios: true


flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/utils/managers/i18n_manager/translations/l10n
  output_dir: lib/utils/managers/i18n_manager/translations/generated

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/flags/
    - assets/images/app_icons/
    - assets/anims/
    - assets/fonts/
    - .env.dev
    - .env.prod

  fonts:
    - family: caprasimo
      fonts:
        - asset: assets/fonts/caprasimo-regular.ttf